In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_excel('Data.xlsx')

In [3]:
data.head()

Sex (F=1)  Rank (1=asst, 2=assoc, 3=full)  Years  PhD  \
0          0                               3     25    1   
1          0                               3     13    1   
2          0                               3     10    1   
3          1                               3      7    1   
4          0                               3     19    0   

   Years (since highest degree)  Salary (USD)  
0                            35         36350  
1                            22         35350  
2                            23         28200  
3                            27         26775  
4                            30         33696

In [4]:
data.columns

Index(['Sex (F=1)', 'Rank (1=asst, 2=assoc, 3=full)', 'Years', 'PhD',
       'Years (since highest degree)', 'Salary (USD)'],
      dtype='object')

In [5]:
from sklearn.linear_model import LinearRegression

In [6]:
reg = LinearRegression()

In [7]:
X = data[['Sex (F=1)', 'Rank (1=asst, 2=assoc, 3=full)', 'Years', 'PhD',
       'Years (since highest degree)']]
y = data[['Salary (USD)']]

In [8]:
reg.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [9]:
reg.coef_

array([[ 1241.7924996 ,  5586.18144952,   482.85976783, -1331.64406341,
         -128.79057354]])

In [10]:
reg.intercept_

array([11410.14654726])

In [11]:
reg.predict([[1, 1, 10, 0, 15]])

array([[21134.85957149]])

In [12]:
pred = reg.predict(X)

In [13]:
from scipy import stats

In [14]:
t, p = stats.ttest_ind(y,pred)

In [15]:
float(p)

0.9999999999999974